### ISSUE TITLE
Add usage examples

### ISSUE THREAD

**Issue by dgellow** [LouisTakePILLz/ArgumentParser#5]
Hi,

In the Readme you link to the wiki for usage documentation but the wiki doesn't exist
## In Readme

<img width="218" alt="screen shot 2016-10-26 at 16 25 03" src="https://cloud.githubusercontent.com/assets/2451004/19730028/315011b4-9b99-11e6-877c-1540efd61571.png">
## Wiki page

<img width="1002" alt="screen shot 2016-10-26 at 16 25 07" src="https://cloud.githubusercontent.com/assets/2451004/19730031/32b85930-9b99-11e6-925d-e0ce894b7fbb.png">

**Comment by notpeelz** [comment]
Thanks for letting me know! I've been meaning to work on this project lately, but never got around to it.
I'll definitely add some examples now that there's an actual demand for it.

In the meantime, you can refer to the test suite as a makeshift (since the test suite is more of a "dev playground" than anything else).

See [ParameterDisambiguationTestUnit.cs](https://github.com/LouisTakePILLz/ArgumentParser/tree/f44caeb6d744870cd2772facdb0bae8154979e0d/ArgumentParserTest/ParameterDisambiguationTestUnit.cs) and [ContextTestUnit.cs](https://github.com/LouisTakePILLz/ArgumentParser/tree/f44caeb6d744870cd2772facdb0bae8154979e0d/ArgumentParserTest/ContextTestUnit.cs) to get an idea how to use the library in "standard mode" and "reflective mode", respectively.

**Comment by dgellow** [comment]
Yes, I already read the test suite :)
